# fly.toml app configuration file generated for gst-invoice-app-wild-feather-8989 on 2024-11-07T16:06:51+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gst-invoice-app-wild-feather-8989'
primary_region = 'bom'

[build]

[env]
  MONGO_URI = 'mongodb+srv://soyal:xlZbWx90Irbr6Tfn@clusterddc.j8lav.mongodb.net/DDC-SHOPIFY-GST-APP?retryWrites=true&w=majority'
  PORT = "8081"
  SCOPES = 'read_orders,read_products,write_products'
  SHOPIFY_API_KEY = 'f91cb213006ab6fb5448b00b9a44c33c'
  HOST = 'https://gst-invoice-app-wild-feather-8989.fly.dev'
  SUPPORT_EMAIL = 'delhiappco@gmail.com'
  SUPPORT_PASSWORD = 'qlei dunz wqsb mzad'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
