# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f91cb213006ab6fb5448b00b9a44c33c"
name = "GST Invoice App"
handle = "gst-invoice-app-2"
application_url = "https://side-roommates-icq-congratulations.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devstore134.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://dropped-floppy-rage-behaviour.trycloudflare.com/auth/callback",
  "https://dropped-floppy-rage-behaviour.trycloudflare.com/auth/shopify/callback",
  "https://dropped-floppy-rage-behaviour.trycloudflare.com/api/auth/callback",
  "https://grave-giving-appliances-chem.trycloudflare.com/auth/callback",
  "https://grave-giving-appliances-chem.trycloudflare.com/auth/shopify/callback",
  "https://grave-giving-appliances-chem.trycloudflare.com/api/auth/callback",
  "https://wound-lg-integrated-opponents.trycloudflare.com/auth/callback",
  "https://wound-lg-integrated-opponents.trycloudflare.com/auth/shopify/callback",
  "https://wound-lg-integrated-opponents.trycloudflare.com/api/auth/callback",
  "https://disabilities-todd-wr-commentary.trycloudflare.com/auth/callback",
  "https://disabilities-todd-wr-commentary.trycloudflare.com/auth/shopify/callback",
  "https://disabilities-todd-wr-commentary.trycloudflare.com/api/auth/callback",
  "https://technology-uruguay-broadcasting-mystery.trycloudflare.com/auth/callback",
  "https://technology-uruguay-broadcasting-mystery.trycloudflare.com/auth/shopify/callback",
  "https://technology-uruguay-broadcasting-mystery.trycloudflare.com/api/auth/callback",
  "https://divided-remembered-specifically-dump.trycloudflare.com/auth/callback",
  "https://divided-remembered-specifically-dump.trycloudflare.com/auth/shopify/callback",
  "https://divided-remembered-specifically-dump.trycloudflare.com/api/auth/callback",
  "https://side-roommates-icq-congratulations.trycloudflare.com/auth/callback",
  "https://side-roommates-icq-congratulations.trycloudflare.com/auth/shopify/callback",
  "https://side-roommates-icq-congratulations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
