# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "78fbc68547f4cc8682944642dc9284c8"
<<<<<<< HEAD
application_url = "https://roots-recording-celebrities-base.trycloudflare.com"
=======
application_url = "https://wireless-richards-too-dominican.trycloudflare.com"
>>>>>>> 590f8d8813a3f9d0fb428ec9bcf221d1a8a8a991
embedded = true
name = "Indian GST App under dev"
handle = "indian-gst-app-under-dev-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devstore134.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://roots-recording-celebrities-base.trycloudflare.com/auth/callback",
  "https://roots-recording-celebrities-base.trycloudflare.com/auth/shopify/callback",
  "https://roots-recording-celebrities-base.trycloudflare.com/api/auth/callback"
=======
  "https://wireless-richards-too-dominican.trycloudflare.com/auth/callback",
  "https://wireless-richards-too-dominican.trycloudflare.com/auth/shopify/callback",
  "https://wireless-richards-too-dominican.trycloudflare.com/api/auth/callback"
>>>>>>> 590f8d8813a3f9d0fb428ec9bcf221d1a8a8a991
]

[pos]
embedded = false
