# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f91cb213006ab6fb5448b00b9a44c33c"
name = "Indian GST Invoice"
handle = "IndianGSTInvoice"
application_url = "https://indian-gst-invoice-ddc-snowy-hill-6969.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devstore134.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,write_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://indian-gst-invoice-ddc-snowy-hill-6969.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
