# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f91cb213006ab6fb5448b00b9a44c33c"
name = "GST Invoice App"
handle = "gst-invoice-app-2"
application_url = "https://nigeria-headset-pens-relax.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devstore134.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://nigeria-headset-pens-relax.trycloudflare.com/auth/callback",
  "https://nigeria-headset-pens-relax.trycloudflare.com/auth/shopify/callback",
  "https://nigeria-headset-pens-relax.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
