# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f91cb213006ab6fb5448b00b9a44c33c"
name = "Indian GST Invoice"
handle = "gst-invoice-app-2"
<<<<<<< HEAD
application_url = "https://dust-owen-streams-laughing.trycloudflare.com"
=======
application_url = "https://genetics-executed-julian-emission.trycloudflare.com"
>>>>>>> b334ddccda2a8467924a590b7e31b9501ea8cf4a
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devstore134.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://dust-owen-streams-laughing.trycloudflare.com/auth/callback",
  "https://dust-owen-streams-laughing.trycloudflare.com/auth/shopify/callback",
  "https://dust-owen-streams-laughing.trycloudflare.com/api/auth/callback"
=======
  "https://genetics-executed-julian-emission.trycloudflare.com/auth/callback",
  "https://genetics-executed-julian-emission.trycloudflare.com/auth/shopify/callback",
  "https://genetics-executed-julian-emission.trycloudflare.com/api/auth/callback"
>>>>>>> b334ddccda2a8467924a590b7e31b9501ea8cf4a
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
